#!/usr/bin/env python3

# Based on http://candidtim.github.io/appindicator/2014/09/13/ubuntu-appindicator-step-by-step.html

import os
import signal
import gi
import subprocess

gi.require_version("Gtk", "3.0")
gi.require_version('AppIndicator3', '0.1')

from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator

APPINDICATOR_ID = 'hdmi-switcher'

def main():
    icon_path = os.path.dirname(os.path.abspath(__file__)) + '/television.svg'
    indicator = appindicator.Indicator.new(
        APPINDICATOR_ID,
        icon_path,
        appindicator.IndicatorCategory.SYSTEM_SERVICES
    )
    indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
    indicator.set_menu(build_menu())
    gtk.main()

def build_menu():
    menu = gtk.Menu()

    item_enable_hdmi_screen = gtk.MenuItem("Enable HDMI Screen")
    item_enable_hdmi_screen.connect('activate', enable_hdmi_screen)
    menu.append(item_enable_hdmi_screen)

    item_enable_hdmi_sound = gtk.MenuItem("Enable HDMI sound")
    item_enable_hdmi_sound.connect('activate', enable_hdmi_sound)
    menu.append(item_enable_hdmi_sound)

    item_enable_desktop_screen = gtk.MenuItem("Enable Desktop screen")
    item_enable_desktop_screen.connect('activate', enable_desktop_screen)
    menu.append(item_enable_desktop_screen)

    item_enable_desktop_sound = gtk.MenuItem("Enable Desktop sound")
    item_enable_desktop_sound.connect('activate', enable_desktop_sound)
    menu.append(item_enable_desktop_sound)

    item_quit = gtk.MenuItem('Quit')
    item_quit.connect('activate', quit)
    menu.append(item_quit)

    menu.show_all()
    return menu

def call_bash(cmd):
    p = subprocess.Popen(
        cmd,
        shell=True,
        stdout=subprocess.PIPE
    )
    out, err = p.communicate()
    return out.decode('utf-8').replace('\n', '')

# To detect video devices run: xrandr
def enable_hdmi_screen(source):
    call_bash('xrandr --output DVI-0 --off\nxrandr --output HDMI-0 --auto --right-of DVI-1')

def enable_desktop_screen(source):
    call_bash('xrandr --output HDMI-0 --off\nxrandr --output DVI-0 --auto --right-of DVI-1')

def get_hdmi_sound_index():
    return call_bash('pactl list short sinks | grep hdmi | grep -o -E \'^[0-9]+\'')

def get_desktop_sound_index():
    return call_bash('pactl list short sinks | grep analog | grep -o -E \'^[0-9]+\'')

# To detect audio devices run: pactl list short sinks
def enable_hdmi_sound(source):
    index = get_hdmi_sound_index()
    call_bash('./change_audio.sh ' + index)

def enable_desktop_sound(source):
    index = get_desktop_sound_index()
    call_bash('./change_audio.sh ' + index)

def quit(source):
    gtk.main_quit()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    main()

